<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>bin\Debug\net8.0\dokumentacja.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiveCharts.Wpf.NetCore3" Version="0.9.8" />
  </ItemGroup>

</Project>
